"""Gen3 タイプ相性テーブル
汎用バトルAIの基盤。ダメージ計算に使用。
"""

# タイプID (Gen3)
NORMAL = 0
FIGHTING = 1
FLYING = 2
POISON = 3
GROUND = 4
ROCK = 5
BUG = 6
GHOST = 7
STEEL = 8
FIRE = 10
WATER = 11
GRASS = 12
ELECTRIC = 13
PSYCHIC = 14
ICE = 15
DRAGON = 16
DARK = 17

TYPE_NAMES = {
    0: "Normal", 1: "Fighting", 2: "Flying", 3: "Poison",
    4: "Ground", 5: "Rock", 6: "Bug", 7: "Ghost",
    8: "Steel", 10: "Fire", 11: "Water", 12: "Grass",
    13: "Electric", 14: "Psychic", 15: "Ice", 16: "Dragon", 17: "Dark",
}

# 相性倍率: EFFECTIVENESS[攻撃タイプ][防御タイプ] = 倍率
# 2.0 = 効果抜群, 0.5 = 今ひとつ, 0.0 = 効果なし, 1.0 = 等倍
EFFECTIVENESS = {}

def _init_chart():
    """Gen3タイプ相性を初期化"""
    types = list(TYPE_NAMES.keys())
    for atk in types:
        EFFECTIVENESS[atk] = {}
        for dfn in types:
            EFFECTIVENESS[atk][dfn] = 1.0

    # Normal
    EFFECTIVENESS[NORMAL][ROCK] = 0.5
    EFFECTIVENESS[NORMAL][GHOST] = 0.0
    EFFECTIVENESS[NORMAL][STEEL] = 0.5

    # Fighting
    EFFECTIVENESS[FIGHTING][NORMAL] = 2.0
    EFFECTIVENESS[FIGHTING][FLYING] = 0.5
    EFFECTIVENESS[FIGHTING][POISON] = 0.5
    EFFECTIVENESS[FIGHTING][ROCK] = 2.0
    EFFECTIVENESS[FIGHTING][BUG] = 0.5
    EFFECTIVENESS[FIGHTING][GHOST] = 0.0
    EFFECTIVENESS[FIGHTING][STEEL] = 2.0
    EFFECTIVENESS[FIGHTING][ICE] = 2.0
    EFFECTIVENESS[FIGHTING][DARK] = 2.0
    EFFECTIVENESS[FIGHTING][PSYCHIC] = 0.5

    # Fire
    EFFECTIVENESS[FIRE][FIRE] = 0.5
    EFFECTIVENESS[FIRE][WATER] = 0.5
    EFFECTIVENESS[FIRE][GRASS] = 2.0
    EFFECTIVENESS[FIRE][ICE] = 2.0
    EFFECTIVENESS[FIRE][BUG] = 2.0
    EFFECTIVENESS[FIRE][ROCK] = 0.5
    EFFECTIVENESS[FIRE][DRAGON] = 0.5
    EFFECTIVENESS[FIRE][STEEL] = 2.0

    # Water
    EFFECTIVENESS[WATER][FIRE] = 2.0
    EFFECTIVENESS[WATER][WATER] = 0.5
    EFFECTIVENESS[WATER][GRASS] = 0.5
    EFFECTIVENESS[WATER][GROUND] = 2.0
    EFFECTIVENESS[WATER][ROCK] = 2.0
    EFFECTIVENESS[WATER][DRAGON] = 0.5

    # Grass
    EFFECTIVENESS[GRASS][FIRE] = 0.5
    EFFECTIVENESS[GRASS][WATER] = 2.0
    EFFECTIVENESS[GRASS][GRASS] = 0.5
    EFFECTIVENESS[GRASS][POISON] = 0.5
    EFFECTIVENESS[GRASS][GROUND] = 2.0
    EFFECTIVENESS[GRASS][FLYING] = 0.5
    EFFECTIVENESS[GRASS][BUG] = 0.5
    EFFECTIVENESS[GRASS][ROCK] = 2.0
    EFFECTIVENESS[GRASS][DRAGON] = 0.5
    EFFECTIVENESS[GRASS][STEEL] = 0.5

    # Electric
    EFFECTIVENESS[ELECTRIC][WATER] = 2.0
    EFFECTIVENESS[ELECTRIC][ELECTRIC] = 0.5
    EFFECTIVENESS[ELECTRIC][GRASS] = 0.5
    EFFECTIVENESS[ELECTRIC][GROUND] = 0.0
    EFFECTIVENESS[ELECTRIC][FLYING] = 2.0
    EFFECTIVENESS[ELECTRIC][DRAGON] = 0.5

    # Ice
    EFFECTIVENESS[ICE][FIRE] = 0.5
    EFFECTIVENESS[ICE][WATER] = 0.5
    EFFECTIVENESS[ICE][GRASS] = 2.0
    EFFECTIVENESS[ICE][ICE] = 0.5
    EFFECTIVENESS[ICE][GROUND] = 2.0
    EFFECTIVENESS[ICE][FLYING] = 2.0
    EFFECTIVENESS[ICE][DRAGON] = 2.0
    EFFECTIVENESS[ICE][STEEL] = 0.5

    # Ground
    EFFECTIVENESS[GROUND][FIRE] = 2.0
    EFFECTIVENESS[GROUND][ELECTRIC] = 2.0
    EFFECTIVENESS[GROUND][GRASS] = 0.5
    EFFECTIVENESS[GROUND][POISON] = 2.0
    EFFECTIVENESS[GROUND][ROCK] = 2.0
    EFFECTIVENESS[GROUND][BUG] = 0.5
    EFFECTIVENESS[GROUND][FLYING] = 0.0
    EFFECTIVENESS[GROUND][STEEL] = 2.0

    # Psychic
    EFFECTIVENESS[PSYCHIC][FIGHTING] = 2.0
    EFFECTIVENESS[PSYCHIC][POISON] = 2.0
    EFFECTIVENESS[PSYCHIC][PSYCHIC] = 0.5
    EFFECTIVENESS[PSYCHIC][DARK] = 0.0
    EFFECTIVENESS[PSYCHIC][STEEL] = 0.5

    # Bug
    EFFECTIVENESS[BUG][FIRE] = 0.5
    EFFECTIVENESS[BUG][GRASS] = 2.0
    EFFECTIVENESS[BUG][FIGHTING] = 0.5
    EFFECTIVENESS[BUG][POISON] = 0.5
    EFFECTIVENESS[BUG][FLYING] = 0.5
    EFFECTIVENESS[BUG][PSYCHIC] = 2.0
    EFFECTIVENESS[BUG][GHOST] = 0.5
    EFFECTIVENESS[BUG][DARK] = 2.0
    EFFECTIVENESS[BUG][STEEL] = 0.5

    # Rock
    EFFECTIVENESS[ROCK][FIRE] = 2.0
    EFFECTIVENESS[ROCK][ICE] = 2.0
    EFFECTIVENESS[ROCK][FIGHTING] = 0.5
    EFFECTIVENESS[ROCK][GROUND] = 0.5
    EFFECTIVENESS[ROCK][FLYING] = 2.0
    EFFECTIVENESS[ROCK][BUG] = 2.0
    EFFECTIVENESS[ROCK][STEEL] = 0.5

    # Ghost
    EFFECTIVENESS[GHOST][NORMAL] = 0.0
    EFFECTIVENESS[GHOST][GHOST] = 2.0
    EFFECTIVENESS[GHOST][PSYCHIC] = 2.0
    EFFECTIVENESS[GHOST][DARK] = 0.5
    EFFECTIVENESS[GHOST][STEEL] = 0.5

    # Dragon
    EFFECTIVENESS[DRAGON][DRAGON] = 2.0
    EFFECTIVENESS[DRAGON][STEEL] = 0.5

    # Dark
    EFFECTIVENESS[DARK][FIGHTING] = 0.5
    EFFECTIVENESS[DARK][PSYCHIC] = 2.0
    EFFECTIVENESS[DARK][GHOST] = 2.0
    EFFECTIVENESS[DARK][DARK] = 0.5
    EFFECTIVENESS[DARK][STEEL] = 0.5

    # Steel
    EFFECTIVENESS[STEEL][FIRE] = 0.5
    EFFECTIVENESS[STEEL][WATER] = 0.5
    EFFECTIVENESS[STEEL][ELECTRIC] = 0.5
    EFFECTIVENESS[STEEL][ICE] = 2.0
    EFFECTIVENESS[STEEL][ROCK] = 2.0
    EFFECTIVENESS[STEEL][STEEL] = 0.5

    # Flying
    EFFECTIVENESS[FLYING][ELECTRIC] = 0.5
    EFFECTIVENESS[FLYING][GRASS] = 2.0
    EFFECTIVENESS[FLYING][FIGHTING] = 2.0
    EFFECTIVENESS[FLYING][BUG] = 2.0
    EFFECTIVENESS[FLYING][ROCK] = 0.5
    EFFECTIVENESS[FLYING][STEEL] = 0.5

    # Poison
    EFFECTIVENESS[POISON][GRASS] = 2.0
    EFFECTIVENESS[POISON][POISON] = 0.5
    EFFECTIVENESS[POISON][GROUND] = 0.5
    EFFECTIVENESS[POISON][ROCK] = 0.5
    EFFECTIVENESS[POISON][GHOST] = 0.5
    EFFECTIVENESS[POISON][STEEL] = 0.0

_init_chart()


def get_effectiveness(atk_type: int, def_type1: int, def_type2: int = -1) -> float:
    """攻撃タイプ vs 防御タイプ(1-2)の相性倍率を返す"""
    eff = EFFECTIVENESS.get(atk_type, {}).get(def_type1, 1.0)
    if def_type2 >= 0 and def_type2 != def_type1:
        eff *= EFFECTIVENESS.get(atk_type, {}).get(def_type2, 1.0)
    return eff


if __name__ == "__main__":
    # テスト
    print(f"Fire vs Grass: {get_effectiveness(FIRE, GRASS)}x")  # 2.0
    print(f"Water vs Fire: {get_effectiveness(WATER, FIRE)}x")  # 2.0
    print(f"Normal vs Ghost: {get_effectiveness(NORMAL, GHOST)}x")  # 0.0
    print(f"Fighting vs Normal/Ghost: {get_effectiveness(FIGHTING, NORMAL, GHOST)}x")  # 0.0
    print(f"Fire vs Water/Rock: {get_effectiveness(FIRE, WATER, ROCK)}x")  # 0.25
